### ISSUE TITLE
IPv6 addresses cannot connect

### ISSUE THREAD

**Issue by Steve-Mcl** [flowforge/flowforge-device-agent#50]
### Current Behavior

If user has specified !Pv6 address, WS (via MQTT.js) throws an error

Full details in MQTT.JS issue raised here:  https://github.com/mqttjs/MQTT.js/issues/1569

### Expected Behavior

IPv6 addresses should connect

### Steps To Reproduce

* Set broker config in flowforge.yml to use `::1` (or any other IPv6 address)
* Start FlowForge
* regenerate a device credentials, copy to device & run the agent

example yml section for project nodes MQTT Broker Configuration:

```yml
#################################################
# MQTT Broker Configuration                     #
#################################################

broker:
  ## Internal url used by the platform to connect to the broker
  url: mqtt://[::1]:9883
  ## External url used by devices to connect to the broker, if different
  public_url: ws://[::1]:9884
```

### Environment

- FlowForge version: 1.x-git
- Node.js version: 16
- npm version: 8
- Platform/OS: Windows/Linux
- Browser:
